"""add staff attendance

Revision ID: 27a6dc4bfe4f
Revises: 5c69404d6770
Create Date: 2026-10-06 16:43:35.944351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a6dc4bfe4f'
down_revision: Union[str, None] = '5c69404d6770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_staff_attendance_user_date')
    )
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_date'))

    op.drop_table('staff_attendance')
    # ### end Alembic commands ###
