"""add face enrollments

Revision ID: 5c69404d6770
Revises: 19628d1d65ec
Create Date: 2026-10-06 15:46:46.075251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c69404d6770'
down_revision: Union[str, None] = '19628d1d65ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('face_embedding_json', sa.JSON(), nullable=False),
    sa.Column('photo_base64', sa.Text(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enrolled_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_enrollments_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_enrollments_user_id'))

    op.drop_table('face_enrollments')
    # ### end Alembic commands ###
